"""Generates a Databricks Asset Bundle job resource file -- one task per
table -- from the table registry and dependency graph.

This file is a **build artifact**, regenerated by CI on every change to
``metadata/``. It should never be hand-edited: metadata is the single
source of truth for both local execution (via
:class:`~platform_name.engine.runner.TableRunner`) and this generated
Lakeflow Jobs job (Databricks' current name -- as of the 2025/2026
Lakeflow unification -- for what was previously called Databricks
Workflows; the Jobs API and task/``depends_on`` shape this module targets
are unchanged). That is what guarantees the two never drift apart --
they are compiled from the exact same :class:`TableRegistry` and
:class:`DependencyGraph` objects.

Like every other generic component in this framework, this module contains
zero table-specific logic: it only ever reads generic shape (table names,
layers, dependencies) from the registry, never business meaning.

Usage::

    python -m platform_name.deploy.bundle_generator \\
        --output resources/tables_job.yml
"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml

from platform_name.engine.dependency_graph import DependencyGraph
from platform_name.engine.table_registry import TableRegistry

_REPO_ROOT = Path(__file__).resolve().parents[3]
# Metadata lives colocated with processors under `platform_name/tables/`
# (see table_registry.py) -- this default resolves correctly whether run
# from a repo checkout or from an installed wheel, since metadata ships
# inside the package (see pyproject.toml package-data).
DEFAULT_METADATA_ROOT = Path(__file__).resolve().parents[1] / "tables"
DEFAULT_OUTPUT_PATH = _REPO_ROOT / "resources" / "tables_job.yml"

# Must match the console-script name registered in pyproject.toml
# ([project.scripts]) and packaged into the wheel -- never a table-specific
# name, since it is the *same* entry point for every task.
ENTRY_POINT_NAME = "run_single_table"

JOB_RESOURCE_NAME = "platform_name_tables"
JOB_CLUSTER_KEY = "shared_cluster"


def _task_key(fully_qualified_name: str) -> str:
    """Databricks task keys must match ``[\\w\\-]+``; '.' is not allowed, so
    translate e.g. 'gold.returns' -> 'gold__returns'. Purely mechanical --
    carries no business meaning, same rule for every table."""
    return fully_qualified_name.replace(".", "__")


def build_task_definitions(registry: TableRegistry) -> list[dict[str, Any]]:
    """Builds one Databricks task definition per table, wiring `depends_on`
    directly from each table's declared metadata dependencies.

    Only *direct* dependencies are declared here -- Lakeflow Jobs
    resolves transitive ordering itself once direct edges exist, the same
    way :class:`DependencyGraph` does for the in-process runner. The whole
    registry's graph is validated (cycles, missing deps, layer ordering)
    before any task is emitted, so a broken dependency graph fails the
    generator, not a half-deployed job.
    """
    graph = DependencyGraph(registry)
    graph.validate()

    tasks: list[dict[str, Any]] = []
    for definition in registry.list_tables():
        fq_name = definition.fully_qualified_name
        task: dict[str, Any] = {
            "task_key": _task_key(fq_name),
            "job_cluster_key": JOB_CLUSTER_KEY,
            "python_wheel_task": {
                "package_name": "platform_name",
                "entry_point": ENTRY_POINT_NAME,
                "parameters": [
                    "--table",
                    fq_name,
                    "--env",
                    "{{job.parameters.environment}}",
                ],
            },
            "libraries": [{"whl": "../dist/*.whl"}],
        }
        if definition.dependencies:
            task["depends_on"] = [
                {"task_key": _task_key(dependency)} for dependency in definition.dependencies
            ]
        tasks.append(task)

    return tasks


def build_job_resource(registry: TableRegistry) -> dict[str, Any]:
    """Wraps the generated tasks in a full Databricks Asset Bundle
    ``resources.jobs.<name>`` document.
    """
    return {
        "resources": {
            "jobs": {
                JOB_RESOURCE_NAME: {
                    "name": f"platform_name-tables-${{bundle.target}}",
                    "parameters": [
                        {"name": "environment", "default": "${var.environment}"},
                    ],
                    "job_clusters": [
                        {
                            "job_cluster_key": JOB_CLUSTER_KEY,
                            "new_cluster": {
                                # Placeholder values -- tune per workspace/region.
                                # Kept here (not per-table) since compute sizing
                                # is a deployment concern, not a table concern.
                                "spark_version": "14.3.x-scala2.12",
                                "node_type_id": "Standard_D4a_v4",
                                # "num_workers": 2,

                                "num_workers": 0,
                                "spark_conf": {
                                    "spark.databricks.cluster.profile": "singleNode",
                                    "spark.master": "local[*]",
                                },
                                "custom_tags": {
                                    "ResourceClass": "SingleNode"
                                }
                            },
                        }
                    ],
                    "tasks": build_task_definitions(registry),
                    "email_notifications": {
                        "on_failure": ["${var.alert_email}"],
                    },
                }
            }
        }
    }


class _NoAliasDumper(yaml.SafeDumper):
    """Databricks Asset Bundles don't understand YAML anchors/aliases;
    disable them so the output is always plain, readable YAML."""

    def ignore_aliases(self, data: Any) -> bool:
        return True


def render_yaml(registry: TableRegistry) -> str:
    document = build_job_resource(registry)
    header = (
        "# GENERATED FILE -- do not edit by hand.\n"
        "# Produced by `python -m platform_name.deploy.bundle_generator` from\n"
        "# the metadata/ directory. Re-run the generator (CI does this on every\n"
        "# merge) after any change to table metadata.\n"
    )
    body = yaml.dump(
        document, Dumper=_NoAliasDumper, sort_keys=False, default_flow_style=False
    )
    return header + body


def generate(
    metadata_root: str | Path = DEFAULT_METADATA_ROOT,
    output_path: str | Path = DEFAULT_OUTPUT_PATH,
) -> Path:
    registry = TableRegistry(metadata_root).load()
    rendered = render_yaml(registry)

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    return output


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--metadata-root", default=str(DEFAULT_METADATA_ROOT))
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT_PATH))
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    output_path = generate(metadata_root=args.metadata_root, output_path=args.output)
    print(f"Wrote generated Databricks job resource to {output_path}")


if __name__ == "__main__":
    main()
