"""Generates a Databricks Declarative Automation Bundle job resource file.

This file is a build artifact, regenerated by CI on every change to table
metadata. It should never be hand-edited: metadata is the single source of
truth for both local execution (via TableRunner) and the generated
Databricks Lakeflow Jobs job.

The generated job uses Databricks Serverless compute. Compute sizing is
therefore intentionally absent from this module; Databricks manages the
underlying compute automatically.

Usage::

    python -m platform_name.deploy.bundle_generator \
        --output resources/tables_job.yml
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml

from platform_name.engine.dependency_graph import DependencyGraph
from platform_name.engine.table_registry import TableRegistry

_REPO_ROOT = Path(__file__).resolve().parents[3]
# Metadata lives colocated with processors under `platform_name/tables/`
# (see table_registry.py) -- this default resolves correctly whether run
# from a repo checkout or from an installed wheel, since metadata ships
# inside the package (see pyproject.toml package-data).
DEFAULT_METADATA_ROOT = Path(__file__).resolve().parents[1] / "tables"
DEFAULT_OUTPUT_PATH = _REPO_ROOT / "resources" / "tables_job.yml"

# Must match the console-script name registered in pyproject.toml
# ([project.scripts]) and packaged into the wheel. This is the same
# generic entry point for every table task.
ENTRY_POINT_NAME = "run_single_table"

JOB_RESOURCE_NAME = "platform_name_tables"

# Databricks Serverless environment used by all Python wheel tasks.
#
# Python wheel tasks require an environment when running on serverless.
# The environment version controls the Databricks-managed base environment.
SERVERLESS_ENVIRONMENT_KEY = "default_python"
SERVERLESS_ENVIRONMENT_VERSION = "5"


def _task_key(fully_qualified_name: str) -> str:
    """Convert a table name into a valid Databricks task key.

    Databricks task keys cannot contain '.'. Therefore:

        gold.returns -> gold__returns

    This transformation is purely mechanical and carries no business meaning.
    """
    return fully_qualified_name.replace(".", "__")


def build_task_definitions(
    registry: TableRegistry,
) -> list[dict[str, Any]]:
    """Build one Databricks task definition per registered table.

    Each task:

    - runs the generic `run_single_table` Python wheel entry point;
    - uses the shared Databricks Serverless environment;
    - receives the table's fully-qualified name;
    - receives the bundle's environment parameter;
    - declares only its direct metadata dependencies.

    The DependencyGraph validates the entire graph before any task is emitted.
    """

    graph = DependencyGraph(registry)
    graph.validate()

    tasks: list[dict[str, Any]] = []

    for definition in registry.list_tables():
        fq_name = definition.fully_qualified_name

        task: dict[str, Any] = {
            "task_key": _task_key(fq_name),

            # Python wheel tasks running on Serverless require an environment.
            "environment_key": SERVERLESS_ENVIRONMENT_KEY,

            "python_wheel_task": {
                "package_name": "platform_name",
                "entry_point": ENTRY_POINT_NAME,
                "parameters": [
                    "--table",
                    fq_name,
                    "--env",
                    "{{job.parameters.environment}}",
                ],
            },

            # The wheel is the application artifact produced by the bundle.
            # Keep this as a task library dependency.
            "libraries": [
                {
                    "whl": "../dist/*.whl",
                }
            ],
        }

        if definition.dependencies:
            task["depends_on"] = [
                {
                    "task_key": _task_key(dependency),
                }
                for dependency in definition.dependencies
            ]

        tasks.append(task)

    return tasks


def build_job_resource(
    registry: TableRegistry,
) -> dict[str, Any]:
    """Build the complete Databricks Job resource.

    The job uses Databricks Serverless compute.

    There is intentionally no `job_clusters` or `new_cluster` section here.
    Azure VM size, worker count, Spark master configuration, and related
    infrastructure settings are managed by Databricks Serverless.
    """

    return {
        "resources": {
            "jobs": {
                JOB_RESOURCE_NAME: {
                    "name": f"platform_name-tables-${{bundle.target}}",

                    "parameters": [
                        {
                            "name": "environment",
                            "default": "${var.environment}",
                        },
                    ],

                    # Shared Serverless environment for all Python wheel tasks.
                    "environments": [
                        {
                            "environment_key": SERVERLESS_ENVIRONMENT_KEY,
                            "spec": {
                                "environment_version": SERVERLESS_ENVIRONMENT_VERSION,
                            },
                        }
                    ],

                    "tasks": build_task_definitions(registry),

                    "email_notifications": {
                        "on_failure": [
                            "${var.alert_email}",
                        ],
                    },
                }
            }
        }
    }


class _NoAliasDumper(yaml.SafeDumper):
    """Prevent YAML anchors/aliases in generated Bundle files.

    Databricks Declarative Automation Bundles do not need YAML anchors,
    and plain YAML is easier to inspect and review in Git.
    """

    def ignore_aliases(self, data: Any) -> bool:
        return True


def render_yaml(registry: TableRegistry) -> str:
    """Render the generated Databricks Job resource as YAML."""

    document = build_job_resource(registry)

    header = (
        "# GENERATED FILE -- do not edit by hand.\n"
        "# Produced by `python -m platform_name.deploy.bundle_generator` from\n"
        "# the table metadata. Re-run the generator (CI does this on every\n"
        "# merge) after any change to table metadata.\n"
    )

    body = yaml.dump(
        document,
        Dumper=_NoAliasDumper,
        sort_keys=False,
        default_flow_style=False,
    )

    return header + body


def generate(
    metadata_root: str | Path = DEFAULT_METADATA_ROOT,
    output_path: str | Path = DEFAULT_OUTPUT_PATH,
) -> Path:
    """Generate the Databricks Job resource file."""

    registry = TableRegistry(metadata_root).load()

    rendered = render_yaml(registry)

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")

    return output


def parse_args(
    argv: list[str] | None = None,
) -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(
        description=__doc__,
    )

    parser.add_argument(
        "--metadata-root",
        default=str(DEFAULT_METADATA_ROOT),
    )

    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT_PATH),
    )

    return parser.parse_args(argv)


def main(
    argv: list[str] | None = None,
) -> None:
    """CLI entry point."""

    args = parse_args(argv)

    output_path = generate(
        metadata_root=args.metadata_root,
        output_path=args.output,
    )

    print(
        f"Wrote generated Databricks job resource to {output_path}"
    )


if __name__ == "__main__":
    main()